modLoader="javafml"
# 更新加载器版本范围 (1.20.1 对应 [47,))
loaderVersion="[47,)" 
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues"

[[mods]]
modId="vehicle"
# 使用自动版本替换（推荐）
version="${file.jarVersion}" 
displayName="MrCrayfish's Vehicle Mod"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=vehicle"
displayURL="https://mrcrayfish.com/mods?id=vehicle"
logoFile="vehicle_mod.png"
credits="Phylogeny https://github.com/Phylogeny Mo0dss https://github.com/Moodsss"
authors="MrCrayfish"
description="A mod that adds vehicles into Minecraft!"

# 1.20.1 依赖配置
[[dependencies.vehicle]]
    modId="forge"
    mandatory=true
    # 更新 Forge 版本范围
    versionRange="[47.1.0,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="minecraft"
    mandatory=true
    # 更新 Minecraft 版本范围
    versionRange="[1.20.1,1.21)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="framework"
    mandatory=true
    # 保持版本范围不变（但需要实际1.20.1版本支持）
    versionRange="[0.2.3,)" 
    ordering="AFTER"
    side="BOTH"
[[dependencies.vehicle]]
    modId="posture"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

# 添加其他可选依赖（根据gradle.properties配置）
[[dependencies.vehicle]]
    modId="controllable"
    mandatory=false  # 设为可选
    versionRange="[0.18.0,)"  # 更新到1.20.1版本号
    ordering="AFTER"
    side="BOTH"
[[dependencies.vehicle]]
    modId="configured"
    mandatory=false
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.vehicle]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.7.0,)"
    ordering="AFTER"
    side="BOTH"